"""about author col added

Revision ID: 36194a6a6f5a
Revises: 9e7e33c02a6d
Create Date: 2024-07-31 06:06:19.491240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36194a6a6f5a'
down_revision = '9e7e33c02a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
